version: '3.8'
services:
  socket:
    container_name: matcha_socket
    build:
      context: ./socket
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - app-network
    env_file:
      - .env
    volumes:
      - socket_node_modules:/app/node_modules
      - ./socket/src/:/app/src/
      - ./shared-models/:/app/src/shared-models/

  client:
    container_name: matcha_client
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - client_node_modules:/app/node_modules
      - ./client/src/:/app/src/
      - ./shared-models/:/app/src/shared-models/

  api:
    container_name: matcha_api
    build: 
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network
      - db-network
    depends_on:
      - postgres
    env_file:
      - .db.env
      - .env
    volumes:
      - api_node_modules:/app/node_modules
      - ./api/src/:/app/src/
      - ./shared-models/:/app/src/shared-models/

  postgres:
    container_name: matcha_postgres
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db-network
    env_file:
      - .db.env

  pgadmin:
    container_name: matcha_pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .pgadmin.env
    ports:
      - "5050:80"
    networks:
      - db-network

  nginx:
    container_name: matcha_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - client
      - api
      - socket

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  postgres_data:
  client_node_modules:
  api_node_modules:
  socket_node_modules:
