version: '3.8'
services:
  socket:
    build: ./socket
    ports:
      - "${SOCKET_PORT}:3002"
    depends_on:
      - api
    networks:
      - app-network


  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "${CLIENT_PORT}:4200"
    networks:
      - app-network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:3000"
    networks:
      - app-network
    depends_on:
      - mariadb
    env_file:
      - .db.env

  mariadb:
    image: mariadb:10.6.4
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .db.env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - app-network
    depends_on:
      - client
      - api
networks:
  app-network:
    driver: bridge
volumes:
  mariadb_data:
